### ISSUE TITLE
Redundancy in checking the existence of the field for the conditions startswith, contains and endswith

### ISSUE THREAD

**Issue by rpfontana** [obviouslynotraffa/pySigma-backend-surrealql#1]
SurrealDB provides some built-in string function for checking if a string `startswith`, `contains`, `endswith` another string. If these functions are passed the field to check as a parameter, but the field is **NONE** (a situation that can occur due to a schemaless design), SurrealDB throws an error. For this reason, it is necessary to add a check for the existence of the field itself (e.g. "field IS NOT NONE").

The issue is related to how this check is implemented in the developed backend. Currently, the check is performed for every possible value in the list, rather than just once before processing, which makes it redundant. 

Below is an example of the current output and the desired output.

```
title: Test
status: test
logsource:
    category: test_category
    product: test_product
detection:
    sel:
        fieldA|startswith:
            - valueA
            - valueB
            - valueC
    condition: sel
``` 

#### Current output

``` 
SELECT * FROM <TABLE_NAME> WHERE (fieldA IS NOT NONE AND string::starts_with(fieldA,'valueA')) OR (fieldA IS NOT NONE 
AND string::starts_with(fieldA,'valueB')) OR (fieldA IS NOT NONE AND string::starts_with(fieldA,'valueC')); 
```

#### Desired output

```
SELECT * FROM <TABLE_NAME> WHERE fieldA IS NOT NONE AND (string::starts_with(fieldA,'valueA') OR string::starts_with(fieldA,'valueB') OR string::starts_with(fieldA,'valueC'));
```
